pod 'MBProgressHUD', '~> 0.9.1'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'KVOController'
pod 'SDWebImage'
pod 'Mantle'
pod 'MJRefresh'
pod 'MJExtension'
pod 'HCSStarRatingView', '~> 1.4.4'
pod 'PBWebViewController'
pod 'SDCycleScrollView','~> 1.64'